#!/bin/bash

if [ ! -d "/opt/phoenix-@VERSION@" ]; then
    mkdir -p /opt/phoenix-@VERSION@
fi

if [ ! -d "/opt/phoenix-data" ]; then
    mkdir -p /opt/phoenix-data
    chown -R phoenixuser:phoenixuser /opt/phoenix-data
fi

# Sort out file permissions
if [ ! -h "/opt/phoenix" ] ;then
    ln -s /opt/phoenix-@VERSION@ /opt/phoenix
    chown -R phoenixuser:phoenixuser /opt/phoenix
else
    echo "Switch /opt/phoenix to /opt/phoenix-@VERSION@ and upgrade manually."
fi

if [ ! -f "/opt/phoenix-@VERSION@/releases/@VERSION@/vm.args" ]; then
    echo "Created /opt/phoenix-@VERSION@/releases/@VERSION@/vm.args from template"
    cp -p "/opt/phoenix-@VERSION@/releases/@VERSION@/vm.args.template" "/opt/phoenix-@VERSION@/releases/@VERSION@/vm.args"
else
    echo "/opt/phoenix-@VERSION@/releases/@VERSION@/vm.args exists and not modified"
fi

if [ ! -f "/opt/phoenix-@VERSION@/releases/@VERSION@/sys.config" ]; then
    echo "Created /opt/phoenix-@VERSION@/releases/@VERSION@/sys.config from template"
    cp -p "/opt/phoenix-@VERSION@/releases/@VERSION@/sys.config.template" "/opt/phoenix-@VERSION@/releases/@VERSION@/sys.config"
else
    echo "/opt/phoenix-@VERSION@/releases/@VERSION@/sys.config exists and not modified"
fi

chown -R phoenixuser:phoenixuser /opt/phoenix-@VERSION@
chown -R phoenixuser:phoenixuser /opt/phoenix_datastore/leveldb-data/

# reload sysctl.d files
echo "reloading sysctl settings after change"
sysctl --system > /dev/null

# Uncomment to allow beam application to bind to lower ports
# sudo setcap CAP_NET_BIND_SERVICE=+eip /opt/phoenix-@VERSION@/erts*/bin/beam.smp

systemctl daemon-reload

