#!/bin/bash

# create a system user for the process,
# modern useradd will add the default group too
if [[ ! $(id phoenixuser 2>/dev/null) ]] ;then
    # create an phoenix system account without creating home directory
    /usr/sbin/useradd --system -M --home-dir /opt/phoenix -s /bin/bash phoenixuser
fi
